# Generated by Django 5.2.6 on 2025-09-04 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hotplace',
            old_name='added_on',
            new_name='added_at',
        ),
    ]
